"""
This file is automatically generated by autosetup.py
Please edit the marked area only. Other areas will be
overwritten when autosetup is rerun.
"""

from setuptools import setup

params = dict(
    name='xdrive',
    description='Portable drive that can be moved between AWS instances',
    version='1.2.60',
    url='ssh://git@github.com/simonm3/xdrive.git',
    install_requires={'PyYAML', 'boto3',
                      'Fabric3', 'Fabric', 'notebook', 'pandas'},
    packages=['xdrive'],
    data_files=[('./etc/xdrive', ['version', 'config.yaml',
                                  'examples.ipynb', 'readme.md', 'licence.txt'])],
    py_modules=[],
    include_package_data=True,
    scripts=None,
    setup_requires=['setuptools_git >= 0.3'])

########## EDIT BELOW THIS LINE ONLY ##########

# pipreqs bug identifies this as well as the correct fabric3
params["install_requires"].remove("Fabric")

########## EDIT ABOVE THIS LINE ONLY ##########

setup(**params)
