# setup container for jupyter and analysis

FROM kaggle/python
COPY jupyter_notebook_config.py /root/.jupyter
COPY .ssh /root
RUN git clone https://github.com/simonm3/basics.git
RUN git clone https://github.com/simonm3/analysis.git
RUN python basics/pathconfig.py
ENTRYPOINT jupyter notebook
EXPOSE 8888